### PR TITLE
77 Run tests before commit as precommit hook

### PR DESCRIPTION
**Pull request by DrSkunk**
Implements #77

### CODE REVIEW

**Review by SelleslaghGianni — DISMISSED** [review]

**Comment by woutermeuwis** [comment]
Big fan of this one :D
But if i understand correctly, we have to run a command to set up the hook?
We might want to add that to the readme

**Review by woutermeuwis — CHANGES_REQUESTED** [review]
Big fan of this one :D
But if i understand correctly, we have to run a command to set up the hook?
We might want to add that to the readme

**Comment by SelleslaghGianni** [comment]
I only had to run an npm install, since there is a new dependency @woutermeuwis

**Comment by woutermeuwis** [comment]
> I only had to run an npm install, since there is a new dependency @woutermeuwis

Then what does 'npm prepare' do? :D

**Comment by SelleslaghGianni** [comment]
> Then what does 'npm prepare' do? :D

Good question :P

**Comment by DrSkunk** [comment]
> > I only had to run an npm install, since there is a new dependency @woutermeuwis
> 
> Then what does 'npm prepare' do? :D

Sorry, did not see the updates on this repo!
[`npm prepare` is a special lifecycle hook](https://github.com/Stremio/stremio-web.git) which is automatically run when you do an `npm install`. If wanted I can add info about this in the readme?

**Comment by woutermeuwis** [comment]
> > > I only had to run an npm install, since there is a new dependency @woutermeuwis
> > 
> > 
> > Then what does 'npm prepare' do? :D
> 
> Sorry, did not see the updates on this repo! [`npm prepare` is a special lifecycle hook](https://github.com/Stremio/stremio-web.git) which is automatically run when you do an `npm install`. If wanted I can add info about this in the readme?

would be great, the fact that the hook might prevent new maintainers from comitting might be confusing otherwise :)

**Review by woutermeuwis — APPROVED** [review]

**Comment by DrSkunk** [comment]
Closes #78

**Comment by DrSkunk** [comment]
Closes issue #77

**Pull request merged**
